name: Deploy

on:
  push:
    tags:
      - 'V*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TAG_NAME: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && github.ref }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'

      - name: Install dependencies and build 🔧 
        run: |
          cd blogsaurus
          yarn install --frozen-lockfile 
          yarn build 

      - name: Deploy 🚀
        if: 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: blogsaurus/build/
      
      - name: Extract Tag name
        id: extract_tag
        run:  echo "::set-output name=tag_name::$(echo ${{ github.ref }} | sed 's|refs/tags/||')"
      
      - name: Use Tag Name
        run:  echo "Tag Name is ${{ steps.extract_tag.outputs.tag_name }}"


